title: About Me
description: PhD Student | Quantum enthusiast
logo: docs/assets/My_headshot.jpg
# Personal Information
links:
  - email: "yourname@example.com"
cv: "https://yourwebsite.com/cv.pdf"


theme: jekyll-theme-minimal

