title: About Me
description: PhD Student | Quantum enthusiast
logo: docs/assets/My_headshot.jpg
# Personal Information
links:
  -email: "isujeremiah@ou.edu"
cv: "https://yourwebsite.com/your-cv.pdf"


theme: jekyll-theme-minimal

